"""Guard: tracked prose and source carry no em dash (U+2014).

The FluxTech family writes no em dashes; a sentence takes the punctuation it
needs (period, comma, colon, parentheses). An en dash in a numeric range
(N = 64–4096) is a different character and is allowed. `docs/MAP.md` is
excluded: it is generated by `repo-outline`, whose own banner is fixed upstream.
"""
import subprocess
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
EM_DASH = "—"
SUFFIXES = {".md", ".py", ".yml", ".yaml", ".toml", ".html", ".css"}
EXCLUDED = {"docs/MAP.md"}


def _tracked_files():
    out = subprocess.run(
        ["git", "ls-files"], cwd=REPO_ROOT, capture_output=True, text=True, check=True,
    ).stdout.split("\n")
    return [f for f in out if f and Path(f).suffix in SUFFIXES and f not in EXCLUDED]


def test_no_em_dash_in_tracked_text():
    hits = []
    for rel in _tracked_files():
        text = (REPO_ROOT / rel).read_text(encoding="utf-8")
        for n, line in enumerate(text.splitlines(), 1):
            if EM_DASH in line:
                hits.append(f"{rel}:{n}: {line.strip()}")
    assert not hits, "em dash (U+2014) found; use a period, comma, colon or parentheses:\n" + "\n".join(hits)
